Repository PrimeDAO/contracts, pull requests merged in 2021-05, with the labels that each got.

#99 Added check to verify that supply is not exceeded
  contracts/seed/Seed.sol
  test/seed.js
Labels: ready for review

#105 removed global truffle
  README.md
  build/contracts/AbsoluteVote.json
  build/contracts/Address.json
  build/contracts/Agreement.json
  build/contracts/Avatar.json
  build/contracts/BalancerProxy.json
  build/contracts/Context.json
  build/contracts/Controller.json
  build/contracts/ControllerCreator.json
  build/contracts/DAOToken.json
  build/contracts/DAOTracker.json
  build/contracts/DaoCreator.json
  build/contracts/ECDSA.json
  build/contracts/ERC20.json
  build/contracts/ERC20Burnable.json
  build/contracts/ERC20Capped.json
  build/contracts/ERC20Detailed.json
  build/contracts/ERC20Mintable.json
  build/contracts/ERC20Mock.json
  build/contracts/FarmFactory.json
  build/contracts/GenericScheme.json
  build/contracts/GenesisProtocol.json
  build/contracts/GenesisProtocolLogic.json
  build/contracts/GlobalConstraintInterface.json
  build/contracts/IBPool.json
  build/contracts/IConfigurableRightsPool.json
  build/contracts/IERC20.json
  build/contracts/IRewardDistributionRecipient.json
  build/contracts/Import.json
  build/contracts/IntVoteInterface.json
  build/contracts/Locking4Reputation.json
  build/contracts/LockingToken4Reputation.json
  build/contracts/Math.json
  build/contracts/Migrations.json
  build/contracts/MinterRole.json
  build/contracts/Ownable.json
  build/contracts/PriceOracle.json
  build/contracts/PriceOracleInterface.json
  build/contracts/PrimeToken.json
  build/contracts/ProposalExecuteInterface.json
  build/contracts/RealMath.json
  build/contracts/ReentrancyGuard.json
  build/contracts/RepRedeemer.json
  build/contracts/Reputation.json
  build/contracts/Roles.json
  build/contracts/SafeERC20.json
  build/contracts/SafeMath.json
  build/contracts/Seed.json
  build/contracts/SeedFactory.json
  build/contracts/StakingRewards.json
  build/contracts/UniversalScheme.json
  build/contracts/UniversalSchemeInterface.json
  build/contracts/VotingMachineCallbacks.json
  build/contracts/VotingMachineCallbacksInterface.json
  package.json
Labels: ready for review

#110 Fix: rename `buyBack`
  contracts/seed/Seed.sol
  test/seed.js
Labels: ready for review

#111 Fix notify reward amount
  contracts/incentives/FarmFactory.sol
  contracts/incentives/StakingRewards.sol
  test/staking-rewards.js
Labels: ready for review

#115 Issue #81 keep fundingTokens in Seed contract
  contracts/seed/Seed.sol
  test/seed.js
Labels: DO NOT MERGE, ready for review

#117 Issue #79 - Tokens locks are overwritten
  contracts/seed/Seed.sol
  test/seed.js
Labels: DO NOT MERGE, WIP

#119 For Issue #93 - Renamed cap and successMinimum to hardCap and softCap respectively and corrected calculation for seedToken amount.
  contracts/seed/Seed.sol
  contracts/seed/SeedFactory.sol
  test/helpers/index.js
  test/seed-factory-multicall.js
  test/seed-factory.js
  test/seed.js
Labels: ready for review

#127 license and naming refactoring
  build/contracts/AbsoluteVote.json
  build/contracts/Address.json
  build/contracts/Agreement.json
  build/contracts/Avatar.json
  build/contracts/BalancerProxy.json
  build/contracts/Context.json
  build/contracts/Controller.json
  build/contracts/ControllerCreator.json
  build/contracts/DAOToken.json
  build/contracts/DAOTracker.json
  build/contracts/DaoCreator.json
  build/contracts/ECDSA.json
  build/contracts/ERC20.json
  build/contracts/ERC20Burnable.json
  build/contracts/ERC20Capped.json
  build/contracts/ERC20Detailed.json
  build/contracts/ERC20Mintable.json
  build/contracts/ERC20Mock.json
  build/contracts/FarmFactory.json
  build/contracts/GenericScheme.json
  build/contracts/GenesisProtocol.json
  build/contracts/GenesisProtocolLogic.json
  build/contracts/GlobalConstraintInterface.json
  build/contracts/IBPool.json
  build/contracts/IConfigurableRightsPool.json
  build/contracts/IERC20.json
  build/contracts/Import.json
  build/contracts/IntVoteInterface.json
  build/contracts/Locking4Reputation.json
  build/contracts/LockingToken4Reputation.json
  build/contracts/Math.json
  build/contracts/Migrations.json
  build/contracts/MinterRole.json
  build/contracts/Ownable.json
  build/contracts/PriceOracle.json
  build/contracts/PriceOracleInterface.json
  build/contracts/PrimeToken.json
  build/contracts/ProposalExecuteInterface.json
  build/contracts/RealMath.json
  build/contracts/ReentrancyGuard.json
  build/contracts/RepRedeemer.json
  build/contracts/Reputation.json
  build/contracts/Roles.json
  build/contracts/SafeERC20.json
  build/contracts/SafeMath.json
  build/contracts/Seed.json
  build/contracts/SeedFactory.json
  build/contracts/StakingRewards.json
  build/contracts/UniversalScheme.json
  build/contracts/UniversalSchemeInterface.json
  build/contracts/VotingMachineCallbacks.json
  build/contracts/VotingMachineCallbacksInterface.json
  contracts/incentives/FarmFactory.sol
  contracts/incentives/RewardDistributionRecipient.sol
  contracts/incentives/StakingRewards.sol
  contracts/utils/interfaces/IRewardDistributionRecipient.sol
Labels: ready for review

#140 137 fix modifier naming
  contracts/seed/Seed.sol
  package-lock.json
  test/seed.js
Labels: ready for review

#149 Improvement: Updated claimLock(), initialise() now gets seed amount as an argument.
  contracts/seed/Seed.sol
  contracts/seed/SeedFactory.sol
  test/seed-factory-multicall.js
  test/seed-factory.js
  test/seed.js
Labels: ready for review

#161 Seed Module Major Refactor
  contracts/seed/Seed.sol
  contracts/seed/SeedFactory.sol
  test/helpers/index.js
  test/seed-factory-multicall.js
  test/seed-factory.js
  test/seed.js
Labels: ready for review
